name: Build uBlue images
on:
  push:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Build BlueCandle image
        uses: blue-build/github-action@v1 
        with:
          recipe: blue-candle.yml  #
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}  
          registry_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build BlueMango Image
        uses: blue-build/github-action@v1  
        with:
          recipe: blue-mango.yml 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}  
          registry_token: ${{ secrets.GITHUB_TOKEN }}
