name: Build QuickBlue
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ublue-os/bluebuild/.github/workflows/reusable-build.yml@main
    with:
      image-name: "ghcr.io/guhnope/qsblue"
      sign-image: false        # ‚Üê change to true later when you want real signing
    secrets: inherit
